const sidebarSettings = {
  docs: [
    "docs/introduction",
    "docs/set-up-on-your-cloud-provider",
    {
      type: "category",
      label: "Get started with konpyutaika",
      collapsed: true,
      items: [
        "docs/get-started/getting-started/overview",
      ]
    },
    {
      type: "category",
      label: "Deploy Konpyutaika Data Domain",
      collapsed: true,
      items: [
        "docs/deploy/deployments",
      ],
    },
    {
      type: "category",
      label: "Available versions",
      items: [
        "docs/versions/core",
        {
          type: "category",
          label: "Release Notes",
          items: [
            "docs/versions/konpyutaika-release-notes",
            {
              type: "autogenerated",
              dirName: "docs/versions/release-notes",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Frequently asked questions",
      link: {
        type: "generated-index",
        title: "Frequently asked questions",
        description:
          "Our Frequently Asked Questions (FAQs) section is a space where you can find an answer to some questions we get asked a lot (but that we’re happy to answer!).",
        slug: "/docs/faqs",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "faqs",
        },
      ],
    },
  ],
  reference: [
    // {
    //   type: "category",
    //   label: "Project configs",
    //   items: [
    //     "reference/project.yml",
    //   ],
    // },
  ],
  guides: [
    {
      type: "category",
      label: "Best practices",
      link: {
        type: "generated-index",
        title: "Best practice guides",
        description:
          "Learn how Konpyutaika team approaches building projects through our current viewpoints on structure, style, and setup.",
        slug: "/guides/best-practices",
      },
      items: [
        {
          type: "category",
          label: "How we",
          link: {
            type: "doc",
            id: "guides/best-practices/tmp/1-guide-overview",
          },
          items: [
            "guides/best-practices/tmp/tmp",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Migration",
      items: [
        {
          type: "category",
          label: "Versions",
          link: {
            type: "generated-index",
            title: "Version migration guides",
            description:
              "Learn how to upgrade to the latest version.",
            slug: "/guides/migration/versions",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "guides/migration/versions",
            },
          ],
        },
      ],
    },
    // {
    //   type: "category",
    //   label: "Advanced",
    //   items: [],
    // },
  ],
  community: [
    {
      type: "doc",
      id: "community/join",
    },
    {
      type: "category",
      label: "Contributing",
      link: {
        type: "doc",
        id: "community/contribute",
      },
      items: [
        {
          type: "doc",
          label: "Become a contributor",
          id: "community/contribute",
        },
        "community/contributing/contributing-coding",
        "community/contributing/contributing-online-community",
        "community/contributing/contributing-realtime-events",
      ],
    },
    {
      type: "link",
      label: "Events",
      href: "/community/events",
    },
    {
      type: "category",
      label: "Additional resources",
      items: [
        "community/resources/code-of-conduct",
        "community/resources/slack-rules-of-the-road",
        "community/resources/oss-expectations",
        "community/resources/oss-projects",
        "community/resources/contributor-license-agreements",
      ],
    },
  ],
  Glossary: [
    {
      type: "category",
      label: "Glossary",
      link: {
        type: "generated-index",
        title: "Glossary",
        description:
          "The Glossary is a living collection of terms & concepts commonly used in the data industry. You can use and contribute to this resource to educate yourself, your team, and your stakeholders.",
        slug: "/glossary",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "terms",
        },
      ],
    },
  ],
};

module.exports = sidebarSettings;
